### ISSUE TITLE
Install Fails on High Sierra

### ISSUE THREAD

**Issue by frankvm04** [cctbx/cctbx_project#77] opened 2017-10-11 18:48 UTC
Bootstrap install fails on wxPython...

[wxPython_install_log.txt](https://github.com/cctbx/cctbx_project/files/1376807/wxPython_install_log.txt)

**Comment by bkpoon** [comment] 2017-10-11 19:48
What version of Xcode are you using? Do you have any other compilers installed? Did you get a clean install of macOS 10.13 or did you upgrade from 10.12?

I'm running macOS 10.12, but I'm using Xcode 9, which should be the same version for macOS 10.13 and wxPython should compile with Xcode 9. Here is the output from ```clang --version```.

```shell
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by frankvm04** [comment] 2017-10-11 23:47
My Xcode version is 9.0 (9A235).

I haven't installed other compilers knowingly... Since I am early days on the new OS.

This was a clean install of macOS.

My output from clang --version.
```
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I haven't tried installing on my 10.12 machine (I should have), but I bet it is just fine. I would have thought this would have popped up in the wxPython project's issues, but not yet.

**Comment by Anthchirp** [comment] 2017-10-26 08:43
I suspected that 10.13 has same problems as 10.12 but the build still fails with this patch.
https://github.com/cctbx/cctbx_project/commit/5e9bb8889d573704737e810919b729d199164f4f

We will set up our new Mac as 10.13 build server, so need a fix for this relatively soon.
It looks like wxPython 4 could be helpful here? Adding @ndevenish to discussion

**Comment by graeme-winter** [comment] 2017-10-26 08:44
Just hit the same snag, also keen for a resolution :)

**Comment by ndevenish** [comment] 2017-10-26 09:03
Possibly a problem is the ancient version of wxPython and lack of releases for an older version - I know that some of the problems we custom-patch out are fixed in the repository head, but it seems that the 3.x line is abandoned now. Homebrew seems to have High-Sierra compatible 3.x building, so looking at that might be a start:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/wxmac.rb
https://github.com/Homebrew/homebrew-core/blob/master/Formula/wxpython.rb

> It looks like wxPython 4 could be helpful here? Adding @ndevenish to discussion

I'd suggest putting a migration to wxPython 4 on the housekeeping plan, but probably not as an immediate 'fix' to this. It looks infinitely easier to setup/install, is actually supported, It'd be required for Python3 anyway, and doesn't look *that* intensive a problem; I had an investigation at converting dials' image_viewer and it was mostly renames, and a couple of removed interfaces:

https://github.com/ndevenish/cctbx_project/commit/2f6abbae5c2e58fa38f207cd8f6ba4892913b783
https://github.com/ndevenish/dials/commit/bec673804e41d3e32d0bfe6390455981b53c6f12

Although admittedly this wasn't 100% working yet (notably image masking SEGV'd), on the API side it seems relatively simple. 

I'm not sure what else uses wx in the codebase.

**Comment by frankvm04** [comment] 2017-11-01 18:12
Attempted with Xcode v9.1 on the off chance. Unfortunately still no joy...

Xcode 9.1 (9B55)

Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by bkpoon** [comment] 2017-11-01 18:51
10.13.1 is out, so I'll be updating my machine soon and I'll test it out. It looks like the issue is specific to 10.13 as explained by https://stackoverflow.com/questions/46221364/xcode-9-throws-errors-involving-require

**Comment by ndevenish** [comment] 2017-11-03 16:09
This appears to be fixed with https://github.com/ndevenish/cctbx_project/commit/90a1753f116bbc0893524b07e233177edc6d5850 (Hardcoded kernel->OSX Version mapping) and https://github.com/ndevenish/cctbx_project/commit/4947471064877bd06865ef7f976b2de392fc3dba (Tell OSX to continue assigning old names for macros).

Still have some testing to do before ready for pushing.

**Comment by bkpoon** [comment] 2017-11-03 21:55
I updated to 10.13.1 and Nick's commits do work for me. The flag is more sensible than patching the code to remove underscores for macros.

I did some GUI testing and things look fine except for warnings about color profiles. I think the icons in gui_resources may need to be updated to have some sort of color profile by default (e.g. sRGB).

Nick, can you merge your changes into the master branch? The version mapping changes look cleaner as well. Thanks!

**Closed** 2017-11-03 22:07 UTC

**Comment by ndevenish** [comment] 2017-11-03 22:12
Done - it does feel a little brute-force, but is basically what homebrew does - they **literally** apply https://github.com/wxWidgets/wxWidgets/commit/9a610eadcfe.patch?full_index=1 out of the wxWidgets tree.
