### ISSUE TITLE
Add base macOS flags

### ISSUE THREAD

**Issue by bkpoon** [cctbx/cctbx_project#87] opened 2017-11-07 06:39 UTC
Any objections to setting "-stdlib=libc++" and "-mmacosx-version-min=10.7" as default flags for macOS using Xcode/clang? The libc++ library has better support for newer C++ standards (e.g. C++11), but it bumps up the minimum supported version of macOS to 10.7. The flags would apply to CCTBX and the dependencies in base.

**Comment by graeme-winter** [comment] 2017-11-07 07:58
10.7 is still like several major revisions old so not an unreasonable suggestion.

If the arguments for this are strong, we should go for it. The arguments look strong.

In related news - do we have a 10.7 box to verify that this is indeed compatible?

**Comment by bkpoon** [comment] 2017-11-08 00:55
The earliest version we have is 10.9 and I've been testing binaries built on 10.10/10.11 (limited by available hardware for build system) and they work on 10.9. I think most Phenix users are using more recent versions of macOS.

**Comment by bkpoon** [comment] 2017-11-09 06:42
There are compilation failures for wxPython on macOS 10.13 with the "-stdlib=libc++" flag so the minimum macOS version is set back to 10.6 (e23d66f7ff08fba2bbbefc9d7301e3c98e27e6a0).

**Comment by ndevenish** [comment] 2017-11-09 09:42
Do we care about retaining buildability on old OS, or just that users can run it? Because didn't libc++ become the default/only version after a certain OS version?

I'm certainly in favour of trying to move the minimum everything to something C++11 compatible.

In regards to testing; I've been testing the releases on a 10.6 VM (failed to build last time I checked, but as long as the release built on newer OS's worked I wasn't too bothered), and successfully built the last release on  10.10, 10.11 in addition to 10.12. I'm sure the same can be done for 10.7.

**Comment by bkpoon** [comment] 2017-11-09 22:49
Not building on old versions (< 10.9) is fine. Our installers have been built on 10.9 (Xcode 7), but I'm working on moving the builds over to 10.11 (Xcode 8) so that newer versions of Rosetta work with Phenix. I think compatibility with 10.7 and 10.8 is nice, but I don't really test that far back.

Each new version of Xcode has its quirks that need to be sorted out though. It seems that for Xcode 9 (running on 10.12 and 10.13), the "-stdlib" flag causes problems for wxPython (91f955fb41bd9767708541637e4a17a87e62288c).

**Comment by ndevenish** [comment] 2017-11-09 23:16
Perhaps I'm not understanding the problem - as I understood it, from 10.9+ only libc++ was shipped anyway.. so building on anything 10.9+ would automatically pick up libc++? If we don't care about explicitly building on 10.7, 10.8, wouldn't that mean we don't need to fiddle with the stdlib flag at all?

**Comment by bkpoon** [comment] 2017-11-13 16:49
I think for Xcode 7 and 8, that is true, but for Xcode 9, it looks like the -stdlib flag adds some additional language checks. Also, by being more explicit, other people can see what's happening without having to dig into how Xcode behaves.

**Comment by ndevenish** [comment] 2017-11-15 13:07
I think that adding redundant build flags increases the mental cost needed to understand what and why the build system is doing. The build system is already a mostly comment-free mess with build flags and workarounds with no indication why they were added, if they are important, or whether inconsistencies are deliberate, bugs, or just some test code that was accidentally committed. These change have to be carried forwards forever (or as long as this build system doesn't collapse under it's own weight), and there appears to be no apparent reason they are being added now, let alone in three or five years time when a developer unfamiliar with the build looks at it to decide what code is essential.

Moving the minimum forwards is something I'd love - and assume that this is now official? Should this being 10.7 perhaps be more widely discussed/confirmed or is the decision here enough?

Also, since you've added these now, I guess this issue can close?

**Closed** 2017-11-16 19:54 UTC
