### ISSUE TITLE
test tst_fully_buffered_timeout.py unstable

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#235] opened 2018-09-27 08:38 UTC
Observed this test to fail twice out of the last 8 test runs on MacOS.

**Stacktrace**
```
Traceback (most recent call last):
  File "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/libtbx/tst_fully_buffered_timeout.py", line 22, in <module>
    exercise()
  File "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/libtbx/tst_fully_buffered_timeout.py", line 17, in exercise
    test_command("sleep 5", 10, 5)
  File "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/libtbx/tst_fully_buffered_timeout.py", line 11, in test_command
    assert approx_equal(t1-t0, expected_time, 0.5)
AssertionError
```

**Standard Output**

```
approx_equal eps: 0.5
approx_equal multiplier: 10000000000.0
44.5965821743 approx_equal ERROR
5 approx_equal ERROR
```

**Comment by graeme-winter** [comment] 2018-09-27 08:44
Does not surprise - unless you are on a RTOS any timeout system can be fragile and dependent on system load.

**Comment by Anthchirp** [comment] 2018-09-27 08:51
My package https://github.com/DiamondLightSource/python-procrunner which provides a timeout facility, and includes tests, does not have this issue. This is how I went about testing the timeout facility: https://github.com/DiamondLightSource/python-procrunner/blob/master/tests/test_procrunner.py#L10-L26

**Comment by Anthchirp** [comment] 2018-09-27 08:57
On reflection, I am not convinced the issue is with the test...
The output suggests that running ```sleep 5``` with ```easy_run``` with a timeout set to 10 seconds took 45 seconds to run. Yes, the computer would be busy when running tests - but busy to an extent to cause such a delay? And then with such a high variance on it to only fail in 2 out of 8 runs?

**Comment by olegsobolev** [comment] 2018-09-27 18:09
The fact that previous 3 checks in the test pass doesn't make any sense as
well... And only on Mac? As far as I know it works fine on all our testing
machines. Any ideas? Maybe we should move it somewhere so it will run at a
different stage?

Oleg.

**Comment by ndevenish** [comment] 2018-10-03 09:50
And again
```
Standard Output
approx_equal eps: 0.5
approx_equal multiplier: 10000000000.0
9.20337510109 approx_equal ERROR
5 approx_equal ERROR
```
Our mac mini is a very slow machine, and has a rather heavy-duty virus scanner. I wouldn't be surprised at the occasional blackouts. Mocking timeouts is usually the only way to be sure of these things in general I think, and has the added bonus of the test running much quicker.

**Comment by phyy-nx** [comment] 2018-10-03 18:14
Hi folks, I'm discussing this with Oleg and Billy.  The idea of this test is to test these functionalities:

- We can kill a process with a timeout
- A process that runs normally with a timeout isn't killed
- Timing things generally works

We realize for the first two, the test isn't doing what we want.  Oleg is going to check return codes to make the test better.

However, it seems reasonable that 'sleep 5 != sleep 45'.  Therefore, is it possible to clean up this mac mini to make the test pass?  Perhaps by reducing the number of processors you are using during testing?

Thanks!

**Comment by phyy-nx** [comment] 2018-10-04 16:54
Hi, sorry I'm trying to understand what's going on here. What does your named pipe example show?  The test does not expect input.  Sending nothing into any python script not expecting input will cause it to hang.  Why do you think the test failing on the mac mini is a fault of the test?

Thanks!!!

**Comment by Anthchirp** [comment] 2018-10-05 07:47
My example may be a red herring.

I tried reproducing the test failure and could not do that on an interactive console, even when running the exact same tests as Jenkins does. My best guess is that there is a difference in the test behaviour when run from an interactive console and from within Jenkins (which, naturally, is non-interactive).

**Comment by Anthchirp** [comment] 2018-10-08 08:06
Unless we can find a proper solution I would suggest disabling the test on mac.

**Comment by phyy-nx** [comment] 2018-10-08 17:05
Hi Markus we don't want to disable this test on macs.  We need a reproducible way to get the test failure so we can address the problem.  If it's only one machine showing the failure, then it's not worth disabling the test for all macs everywhere.  Especially since the test passes on our macs.  Instead the bad machine should be fixed, and if that's not possible, the test can be disabled in Jenkins for just that machine, without modifying the test itself in cctbx.

**Comment by graeme-winter** [comment] 2018-10-09 08:16
OK. Been watching this on and off and I feel like we should find a resolution to this.

The machine is not "special" or "broken" - when run interactively the test passes, when run though CI it fails (sometimes) which is very annoying as the builds now fail and pass on and off. We can disable it in Jenkins by not running module=libtbx tests _at all_ which I do not think is a happy solution. We cannot disable one test at a time in the way libtbx tests work.

A more practical solution could be to add some diagnostics to the output so we can find out why it is failing when it is run - however since we do not use this (we use the proc runner in dials land, which handles this case differently, vide ultra) I am hard pushed to justify investing effort at this end to debug this. 

Would you be able to add some diagnostics to aid debugging i.e. subprocess started at t1, finished at t2, etc. so we have a better idea of the problem?

**Comment by olegsobolev** [comment] 2018-10-09 19:13
Closing by disabling the test in DIALS environment: https://github.com/cctbx/cctbx_project/commit/2aa712326a230ba91f459b6c63a72783bc4124f9

I'm totally fine with anybody adding any diagnostic output without reducing the test functionality (which was suggested earlier). I'm reluctant to add diagnostics myself because I don't know what you need and don't even see the output on your testing machines.

**Closed by olegsobolev** 2018-10-09 19:13 UTC

**Comment by Anthchirp** [comment] 2018-10-10 08:00
Happy with this resolution. Point of information though: Our testing output is visible both as [summary status flag on the commits](https://github.com/cctbx/cctbx_project/commits/master) and in detail via the CI mails to the [cctbx commit mailing list](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=CCTBX-COMMIT)
